### ISSUE TITLE
Add CONTRIBUTING.md to the project

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/wisdom-cli#2]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by TheSussex** [comment]
Can you assign this to me and explain the key points you want the document to contain? @t0xic0der

**Comment by gridhead** [comment]
Hi @TheSussex, thank you for expressing your interest on working on this issue. This repository could do just fine with a generic CONTRIBUTING.md so you would find some pointers here at this documentation https://opensource.guide/code-of-conduct. Also, feel free to leave a star on this repository - should you find it helpful.

**Comment by TheSussex** [comment]
I'll get to it then. Thanks

**Comment by TheSussex** [comment]
Hello again @t0xic0der where do you want the file? The repository's root, docs, or .github directory?

**Comment by gridhead** [comment]
The project's root directory would be just fine.

**Comment by TheSussex** [comment]
The

> Hi @TheSussex, thank you for expressing your interest on working on this issue. This repository could do just fine with a generic CONTRIBUTING.md so you would find some pointers here at this documentation https://opensource.guide/code-of-conduct. Also, feel free to leave a star on this repository - should you find it helpful.

The attached link focuses on code of conduct and since someone else is already working on that, I didn't see any need to include it in the contribution guide. Hope that's fine?

**Comment by gridhead** [comment]
My bad. I kind of overlooked the issue topic. Here you [go](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors).

**Comment by TheSussex** [comment]
> My bad. I kind of overlooked the issue topic. Here you [go](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors).

I already put something together and made a PR before I saw this, please let me know if changes are to be made.

**Comment by TheSussex** [comment]
Hello @t0xic0der  , please review the documentation and let me know if you'd like any changes made.

**Comment by gridhead** [comment]
Closing this on successful merge of #12. Thanks for your contribution.

**Comment by TheSussex** [comment]
Thank you for the opportunity
