### ISSUE TITLE
Add CODE_OF_CONDUCT.md to the project

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/wisdom-cli#3]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by hisandeepangara** [comment]
assign to me and explain a bit.

**Comment by gridhead** [comment]
Hi @sandeep3136, thank you for expressing your interest on working on this issue. I am assigning you this issue. Please take a look at this documentation https://docs.github.com/articles/setting-guidelines-for-repository-contributors/. Also, feel free to leave a star on this repository - should you find it helpful.

**Comment by gridhead** [comment]
Any update on this @sandeep3136?

Would you be up for this @tripathyprateek, should @sandeep3136 renounce assignment or fails to respond within the next 12 hours?

**Comment by hisandeepangara** [comment]
made my PR @t0xic0der

**Comment by hisandeepangara** [comment]
sandeep3136:sandeep3136-patch-1 here is my PR

**Comment by gridhead** [comment]
The PR gets the project a CONTRIBUTING.md (which it already has)

**Comment by gridhead** [comment]
Would you want to take this up @mohitgurav?

**Comment by mohitgurav** [comment]
Yeah. Assign it to me @t0xic0der
