### ISSUE TITLE
Properly catch and deal with "DisambiguationError" exceptions

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/wisdom-cli#6]
The exception handling routines currently employed in the project are too generalized. Handling routines for specific exception would be appreciated.

**Comment by gridhead** [comment]
Would you be willing to pick this up, @VaibhavSaini19?

**Comment by VaibhavSaini19** [comment]
@t0xic0der My plate is a bit full right now, I'll let someone else take it

**Comment by gridhead** [comment]
No problem. How about you @mohitgurav?

**Comment by mohitgurav** [comment]
Sure. Please assign it to me.

**Comment by gridhead** [comment]
Thanks @mohitgurav. I am assigning this issue to you.
