### ISSUE TITLE
Properly catch and deal with "WikipediaException" exceptions

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/wisdom-cli#7]
The exception handling routines currently employed in the project are too generalized. Handling routines for specific exceptions would be appreciated.

**Comment by gridhead** [comment]
Would you be willing to pick this up, @s-katte?

**Comment by mohitgurav** [comment]
If @s-katte is busy with something else, I would like to take it up.

**Comment by s-katte** [comment]
sure @mohitgurav. Sorry for not replying.
