### ISSUE TITLE
Properly catch and deal with "PageError" exceptions

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/wisdom-cli#8]
The exception handling routines currently employed in the project are too generalized. Handling routines for specific exceptions would be appreciated.

**Comment by divyagupta-98** [comment]
Can you please assign this to me?

**Comment by gridhead** [comment]
Hi @divyagupta-98, thank you for expressing your interest in working on this issue. Please take a look at this documentation for assistance https://wikipedia.readthedocs.io/en/latest/code.html. Also, feel free to leave a star on this repository - should you find it helpful.

**Comment by gridhead** [comment]
Any update on this @divyagupta-98?

Would you be up for this @mohitgurav, should @divyagupta-98 renounce assignment or fails to respond within the next 12 hours?

**Comment by divyagupta-98** [comment]
@t0xic0der #17 Raised PR

**Comment by gridhead** [comment]
Resolved #8 via #16.
