### ISSUE TITLE
Properly catch and deal with "HTTPTimeoutError" exceptions

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/wisdom-cli#9]
The exception handling routines currently employed in the project are too generalized. Handling routines for specific exceptions would be appreciated.

**Comment by divyagupta-98** [comment]
I would like to work on this!

**Comment by gridhead** [comment]
Hi @divyagupta-98, thank you for expressing your interest in working on this issue. Please take a look at this documentation for assistance https://wikipedia.readthedocs.io/en/latest/code.html. Also, feel free to leave a star on this repository - should you find it helpful.

**Comment by divyagupta-98** [comment]
Can you please have a look at #11.

**Comment by gridhead** [comment]
Closed #9 via #11.
